-- 1. WhatsApp Message Database (Sessions & Configs)
CREATE TABLE IF NOT EXISTS public.whatsapp_message_database (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    session_name text NOT NULL UNIQUE,
    user_id uuid NOT NULL, -- References auth.users
    active boolean DEFAULT true,
    status text DEFAULT 'created', -- 'created', 'scanned', 'connected', 'invalid'
    reply_message boolean DEFAULT true,
    subscription_status text DEFAULT 'active', -- 'active', 'trial', 'expired'
    text_prompt text DEFAULT 'You are a helpful assistant.',
    qr_code text, -- Base64 QR Code string
    message_credit int DEFAULT 0,
    phone_number text,
    config jsonb
);

-- Enable RLS
ALTER TABLE public.whatsapp_message_database ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own whatsapp sessions" 
ON public.whatsapp_message_database FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own whatsapp sessions" 
ON public.whatsapp_message_database FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own whatsapp sessions" 
ON public.whatsapp_message_database FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own whatsapp sessions" 
ON public.whatsapp_message_database FOR DELETE 
USING (auth.uid() = user_id);


-- 2. WhatsApp Chats (Message History)
CREATE TABLE IF NOT EXISTS public.whatsapp_chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    session_name text NOT NULL,
    sender_id text NOT NULL,
    recipient_id text,
    message_id text UNIQUE NOT NULL,
    text text,
    timestamp bigint,
    status text, -- 'received', 'sent', 'read'
    reply_by text -- 'user', 'bot', 'admin'
);

-- Enable RLS
ALTER TABLE public.whatsapp_chats ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read/write chats (Broad policy for now to prevent blockage)
-- Ideally should join with whatsapp_message_database to check user_id, but for now:
CREATE POLICY "Authenticated users can select chats" 
ON public.whatsapp_chats FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Authenticated users can insert chats" 
ON public.whatsapp_chats FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Authenticated users can update chats" 
ON public.whatsapp_chats FOR UPDATE 
TO authenticated 
USING (true);


-- 3. WhatsApp Contacts (Leads)
CREATE TABLE IF NOT EXISTS public.whatsapp_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    session_name text NOT NULL,
    phone_number text NOT NULL,
    name text,
    last_interaction timestamp with time zone,
    UNIQUE(session_name, phone_number)
);

ALTER TABLE public.whatsapp_contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage contacts" 
ON public.whatsapp_contacts FOR ALL 
TO authenticated 
USING (true);


-- 4. WhatsApp Debounce (Prevent Duplicates)
CREATE TABLE IF NOT EXISTS public.whatsapp_debounce (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    message_id text UNIQUE NOT NULL
);

ALTER TABLE public.whatsapp_debounce ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage debounce" 
ON public.whatsapp_debounce FOR ALL 
TO authenticated 
USING (true);


-- 5. WhatsApp Order Tracking
CREATE TABLE IF NOT EXISTS public.whatsapp_order_tracking (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    session_name text,
    sender_id text,
    product_name text,
    number text,
    location text,
    product_quantity text,
    price text,
    status text DEFAULT 'pending'
);

ALTER TABLE public.whatsapp_order_tracking ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage orders" 
ON public.whatsapp_order_tracking FOR ALL 
TO authenticated 
USING (true);


-- 6. Add Missing Columns (Safe Alter)
-- Run these just in case the tables existed but columns were missing

DO $$ 
BEGIN 
    -- whatsapp_message_database
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='whatsapp_message_database' AND column_name='status') THEN
        ALTER TABLE public.whatsapp_message_database ADD COLUMN status text DEFAULT 'created';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='whatsapp_message_database' AND column_name='qr_code') THEN
        ALTER TABLE public.whatsapp_message_database ADD COLUMN qr_code text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='whatsapp_message_database' AND column_name='reply_message') THEN
        ALTER TABLE public.whatsapp_message_database ADD COLUMN reply_message boolean DEFAULT true;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='whatsapp_message_database' AND column_name='subscription_status') THEN
        ALTER TABLE public.whatsapp_message_database ADD COLUMN subscription_status text DEFAULT 'active';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='whatsapp_message_database' AND column_name='text_prompt') THEN
        ALTER TABLE public.whatsapp_message_database ADD COLUMN text_prompt text DEFAULT 'You are a helpful assistant.';
    END IF;
END $$;
