-- WhatsApp Message Database (Config & Prompts)
-- Replaces fb_message_database for WhatsApp
CREATE TABLE IF NOT EXISTS whatsapp_message_database (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name TEXT NOT NULL UNIQUE, -- Acts as page_id
    user_id UUID REFERENCES auth.users(id),
    active BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'created', -- 'created', 'scanned', 'WORKING', 'STOPPED'
    qr_code TEXT, -- Base64 QR Code string
    text_prompt TEXT,
    image_prompt TEXT,
    wait INTEGER DEFAULT 8, -- Debounce wait time in seconds
    image_detection BOOLEAN DEFAULT TRUE,
    voice_response BOOLEAN DEFAULT TRUE,
    reply_message BOOLEAN DEFAULT TRUE,
    block_emoji TEXT DEFAULT '🛑',
    unblock_emoji TEXT DEFAULT '✅',
    engine TEXT DEFAULT 'WEBJS',
    plan_days INTEGER DEFAULT 30,
    subscription_status TEXT DEFAULT 'trial', -- 'active', 'trial', 'expired'
    subscription_expiry TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WhatsApp Chats (Message History)
-- Replaces fb_chats for WhatsApp
CREATE TABLE IF NOT EXISTS whatsapp_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name TEXT NOT NULL, -- Acts as page_id
    message_id TEXT NOT NULL UNIQUE,
    sender_id TEXT NOT NULL,
    recipient_id TEXT,
    text TEXT,
    timestamp BIGINT,
    status TEXT, -- 'received', 'sent', 'delivered', 'read'
    reply_by TEXT, -- 'user', 'bot', 'admin'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster chat retrieval
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_session_sender ON whatsapp_chats(session_name, sender_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_timestamp ON whatsapp_chats(timestamp DESC);

-- WhatsApp Contacts (Leads)
-- Replaces fb_leads for WhatsApp
CREATE TABLE IF NOT EXISTS whatsapp_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    name TEXT,
    last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(session_name, phone_number)
);

-- WhatsApp Debounce Table (if needed separate from global debounce)
CREATE TABLE IF NOT EXISTS whatsapp_debounce (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WhatsApp Order Tracking
-- Replaces fb_order_tracking for WhatsApp
CREATE TABLE IF NOT EXISTS whatsapp_order_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name TEXT NOT NULL,
    sender_id TEXT,
    product_name TEXT,
    number TEXT,
    location TEXT,
    product_quantity TEXT,
    price TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
