-- 1. WhatsApp Session Configuration Table
CREATE TABLE IF NOT EXISTS whatsapp_message_database (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_name TEXT NOT NULL UNIQUE,
    user_id UUID,
    active BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'created',
    reply_message BOOLEAN DEFAULT FALSE,
    swipe_reply BOOLEAN DEFAULT FALSE,
    order_tracking BOOLEAN DEFAULT FALSE,
    image_detection BOOLEAN DEFAULT FALSE,
    image_send BOOLEAN DEFAULT FALSE,
    audio_detection BOOLEAN DEFAULT FALSE,
    file_upload BOOLEAN DEFAULT FALSE,
    text_prompt TEXT,
    subscription_status TEXT DEFAULT 'active',
    expires_at TIMESTAMP WITH TIME ZONE,
    plan_days INTEGER DEFAULT 30,
    qr_code TEXT,
    api_key TEXT,
    cheap_engine BOOLEAN DEFAULT TRUE,
    block_emoji TEXT,
    unblock_emoji TEXT
);

-- Ensure columns exist (Safe for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'plan_days') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN plan_days INTEGER DEFAULT 30;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'expires_at') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN expires_at TIMESTAMP WITH TIME ZONE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'subscription_status') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN subscription_status TEXT DEFAULT 'active';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'order_tracking') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN order_tracking BOOLEAN DEFAULT FALSE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'text_prompt') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN text_prompt TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'block_emoji') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN block_emoji TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'whatsapp_message_database' AND column_name = 'unblock_emoji') THEN
        ALTER TABLE whatsapp_message_database ADD COLUMN unblock_emoji TEXT;
    END IF;
END $$;

-- 2. WhatsApp Chat History Table
CREATE TABLE IF NOT EXISTS whatsapp_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_name TEXT NOT NULL,
    sender_id TEXT NOT NULL,
    recipient_id TEXT,
    message_id TEXT NOT NULL UNIQUE,
    text TEXT,
    timestamp BIGINT,
    status TEXT,
    reply_by TEXT
);

-- Index for faster history lookup
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_session_sender ON whatsapp_chats(session_name, sender_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_timestamp ON whatsapp_chats(timestamp DESC);

-- 3. WhatsApp Order Tracking Table
CREATE TABLE IF NOT EXISTS whatsapp_order_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_name TEXT NOT NULL,
    sender_id TEXT,
    product_name TEXT,
    number TEXT,
    location TEXT,
    product_quantity TEXT,
    price TEXT,
    status TEXT DEFAULT 'pending'
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_orders_number_date ON whatsapp_order_tracking(number, created_at);

-- 4. WhatsApp Contacts/Leads Table
CREATE TABLE IF NOT EXISTS whatsapp_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    name TEXT,
    last_interaction TIMESTAMP WITH TIME ZONE,
    UNIQUE(session_name, phone_number)
);
