
-- Create label_actions table
create table if not exists label_actions (
    id bigint generated by default as identity primary key,
    page_id text not null, -- Links to specific page/session
    label_name text not null, -- e.g. "admincall", "order", "support"
    ai_action text default 'continue', -- 'continue' (AI talks), 'stop' (AI stops/Handover)
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(page_id, label_name)
);

-- Enable RLS
alter table label_actions enable row level security;

-- Policy: Allow all access (since backend uses service key, but good for future)
create policy "Allow all access" on label_actions for all using (true);
